### ISSUE TITLE
Update fluence to go 1.20 or 1.21

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-k8s#71]
We are going to hit issues using fluence (go 1.19) with other integrations like rainbow (go 1.20) and on our systems (go 1.20), and after #69 should consider updating.

**Comment by vsoch** [comment]
Adding a note for myself:

Here https://github.com/flux-framework/flux-k8s/blob/33ab097efdde140962f3aa0bfd2b7e1dc29fbd3a/src/fluence/utils/utils.go#L144-L149 where we create a subnet, it is within a listing of nodes. My understanding of [subnet zones](https://cloud.google.com/vpc/docs/subnets) (which I need to verify with a node listing) is that we can have multiple nodes under the same subnet. So for this part of the code, we likely need to create a lookup of subnets by name, and only create another one if we haven't already created it. I don't think we do anything with this in the current implementation (so likely no issue) but if we had multiple subnet zones I think we might either get duplicate nodes in the graph with different indices, or something like that. Wanted to put a note here so I don't forget (have a lot in my head at the moment).

**Comment by vsoch** [comment]
@cmisale @milroy I'm working on the second bullet above, and wanted to have discussion about the format that we want. We currently do something like (and please correct me if I'm wrong - I get this confused with jobspec nextgen):

```yaml
version: 1
resources:
  - type: slot
    label: default
    count: 2
    with:
    - type:  core
      count: 16
tasks:
  - command: [ "app" ]
    slot: default
    count:
      per_slot: 1
```

With memory / GPU added if it's defined for the pod. And that is done via parsing one container and then having the slot->count be the number of nodes (I think). If we parse each container individually (which assumes they might be different) I'm wanting to know what that should look like? The only thing that made sense to me was to move the count down to the node, and then to be able to say how many of each node is requested:

```yaml
version: 1
resources:
  - type: slot
    label: default
    with:
    - type: node
      count: 1
      with:
        - type:  core
          count: 4
        - type: gpu
          count: 1
    - type: node
      count: 4
      with:
        - type:  core
          count: 16

tasks:
  - command: [ "app" ]
    slot: default
    count:
      per_slot: 1
```

But I remember there was a reason for having the slot right above the core (and not including the nodes) so I think that might be wrong. That said, I don't know how to enforce a design here with nodes of different types, because the approach that asks for "this many CPU across whatever resources you need" doesn't well capture the multiple (different containers).

If possible, let's have some discussion on the above! I have the next PR well underway but I paused here because I wasn't sure.
